# Generated by Django 4.1.2 on 2022-10-28 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_uploader', models.CharField(max_length=200)),
                ('author_of_book', models.CharField(max_length=100)),
                ('title_of_book', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('pages', models.IntegerField()),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
